# Финальная, гибридная конфигурация для Netlify
[build]
  # Конечная папка для публикации будет называться "dist"
  publish = "dist/"
  
  # Сложная команда, которая делает всё, что нам нужно:
  # 1. Заходит в папку blog, устанавливает зависимости и собирает блог
  # 2. Возвращается в корень проекта
  # 3. Создает финальную папку "dist"
  # 4. Копирует ваш главный index.html в эту папку
  # 5. Создает подпапку "blog" внутри "dist" и копирует туда собранный блог
  command = "cd blog && npm install && npm run build && cd .. && mkdir dist && cp index.html dist/ && cp -r blog/_site/* dist/blog/"
