[build]
  # Финальная папка для публикации
  publish = "dist"
  
  # Команда, которая выполняется из корня
  # Мы убираем "npm install", так как "Package directory" сделает это за нас.
  command = "cd blog && npm run build && cd .. && mkdir dist && cp index.html dist/ && cp -r blog/_site/* dist/blog/"
