# Финальная, рабочая, стандартная конфигурация
[build]
  publish = "dist"
  command = "cd blog && npm install && npx @11ty/eleventy && cd .. && rm -rf dist && mkdir dist && cp index.html script.js _redirects main-style.css dist/ && cp -r blog/_site/. dist/"
