# Финальная, 100% рабочая конфигурация
[build]
  publish = "dist"
  command = "cd blog && npm install && npx @11ty/eleventy && cd .. && mkdir dist && mkdir dist/blog && cp index.html dist/ && cp script.js dist/ && cp _redirects dist/ && cp -r blog/_site/* dist/blog/"
