# Конфигурация сборки для Netlify
[build]
  # Базовая директория: все команды будут выполняться из папки "blog"
  base = "blog/"
  
  # Директория для публикации: куда Eleventy сложит готовый сайт
  publish = "_site/"
  
  # Команда для сборки: сначала установить зависимости, потом собрать блог
  command = "npm install && npm run build"
