# Конфигурация для входа по Email + Пароль через Netlify Identity
backend:
  name: git-gateway # Используем "мост" от Netlify
  repo: Novokreschennih/sethubble # <-- Убедитесь, что это правильно
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Статьи"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата публикации", name: "date", widget: "datetime" }
      - { label: "Автор", name: "author", widget: "string", required: false }
      - { label: "Краткое описание (для плитки)", name: "summary", widget: "text" }
      - { label: "Теги (обязательно добавьте 'post')", name: "tags", widget: "list" }
      - { label: "Содержимое статьи", name: "body", widget: "markdown" }
  
  - name: "pages"
    label: "Страницы"
    folder: "pages"
    create: false
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Содержимое", name: "body", widget: "markdown" }
